server:
  port: 8082
spring:
  application:
    name: service-delivery
  datasource:
    url: jdbc:postgresql://${MS_101_SERVICE_DELIVERY_DB_HOST:localhost}:${MS_101_SERVICE_DELIVERY_DB_PORT:5432}/${MS_101_SERVICE_DELIVERY_DB_NAME:postgres}
    username: ${MS_101_SERVICE_DELIVERY_DB_USER}
    password: ${MS_101_SERVICE_DELIVERY_DB_PASS}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true