server:
  port: 8081
spring:
  application:
    name: Customers Microservice
  datasource:
    url: jdbc:postgresql://${MS_101_SUBSCRIPTION_DB_HOST:localhost}:${MS_101_SUBSCRIPTION_DB_PORT:5432}/${MS_101_SUBSCRIPTION_DB_NAME:postgres}
    username: ${MS_101_SUBSCRIPTION_DB_USER}
    password: ${MS_101_SUBSCRIPTION_DB_PASS}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect